

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListadoDePacientes.aspx.cs" Inherits="Vistas.ListadoDePacientes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
 <style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f0f2f5;
        margin: 0;
        padding: 20px;
    }

    .auto-style2 {
        max-width: 1200px;
        margin: 0 auto;
        background-color: #ffffff;
        padding: 25px;
        border-radius: 10px;
        box-shadow: 0 6px 12px rgba(0,0,0,0.1);
            width: 1433px;
        }

    .auto-style1 {
        background-color: #2a6db0;
        color: white;
        font-weight: bold;
        border: none;
        padding: 10px 16px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 0.95rem;
        transition: background-color 0.3s ease;
    }

    .auto-style1:hover {
        background-color: #1f578a;
    }

    .usuario-label {
        font-weight: 600;
        color: #333;
    }

    input[type="text"], select {
        padding: 8px;
        width: 200px;
        border-radius: 5px;
        border: 1px solid #ccc;
        font-size: 0.95rem;
        margin-right: 10px;
    }

    .aspNet-GridView {
        margin-top: 20px;
    }

        .btn-link {
            display: inline-block;
            margin-top: 10px;
            font-weight: bold;
            color: #0099ff;
            text-decoration: none;
        }

        .auto-style3 {
         border-style: none;
         border-color: inherit;
         border-width: medium;
         background-color: #2a6db0;
         color: white;
         font-weight: bold;
         padding: 10px 16px;
         border-radius: 5px;
         cursor: pointer;
         font-size: 0.95rem;
         transition: background-color 0.3s ease;
         margin-left: 0px;
     }
     
        </style>

    </head>
<body>
        <form id="form1" runat="server">
        <div class="auto-style2">

           
                <div style="display: flex; align-items: center; gap: 10px;">
    <asp:Button ID="Button2" runat="server" CssClass="auto-style1" Text="Volver al menú" Width="133px" OnClick="Button2_Click" />
    <asp:Label ID="lblNombreUsuario" runat="server" CssClass="usuario-label" Font-Size="Large" /></div>
                <br />
                <br />
                <asp:Label ID="Label2" runat="server" Text="Listado de pacientes " Font-Bold="True" Font-Size="XX-Large"></asp:Label>
                <br />
                <asp:Label ID="Label1" runat="server" Text="Buscar por DNI" Font-Size="Small"></asp:Label>
                <br />
                <asp:TextBox ID="txtFiltrar" runat="server"></asp:TextBox>
                <br />
                <asp:RequiredFieldValidator ID="rfvDNI" runat="server" ControlToValidate="txtFiltrar" ErrorMessage="Ingrese un DNI" ForeColor="Red" ValidationGroup="grupo1"></asp:RequiredFieldValidator>
                <br />
                <asp:Button ID="btnFiltrar" runat="server" CssClass="auto-style1" Text="Filtrar" Width="113px" OnClick="btnFiltrar_Click" ValidationGroup="grupo1" />
                <br />
                Buscar por Nombre: <br />
                <asp:TextBox ID="txtFiltrarNombre" runat="server"></asp:TextBox>
                <br />
                <br />
                <asp:Button ID="btnFiltrarNombre" runat="server" CssClass="auto-style1" Text="Filtrar" Width="113px" OnClick="btnFiltrarNombre_Click" ValidationGroup="grupo2" />
                <br />
                <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtFiltrarNombre" ErrorMessage="Ingrese un nombre" ForeColor="Red" ValidationGroup="grupo2"></asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Button ID="btnMostrarTodo" runat="server" CssClass="auto-style3" Text="Mostrar todos" Width="158px" OnClick="btnMostrarTodo_Click" />
                <br />
                <asp:Label ID="lbMensaje" runat="server"></asp:Label>
                <br />
                <asp:GridView ID="gv_pacientes" runat="server" AutoGenerateColumns="False" AllowPaging="true" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="5" CssClass="auto-style3" Font-Size="Small" Height="19px" Width="16px" OnPageIndexChanging="gv_pacientes_PageIndexChanging" OnRowEditing="gv_pacientes_RowEditing" OnRowUpdating="gv_pacientes_RowUpdating" OnRowCancelingEdit="gv_pacientes_RowCancelingEdit" OnRowDeleting="gv_pacientes_RowDeleting">
                    <Columns>
                        <asp:TemplateField HeaderText="DNI">
                            <ItemTemplate>
                                <asp:Label ID="lbl_DNI" runat="server" Text='<%# Bind("DNI_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NOMBRE">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_nombrePaciente" runat="server" Text='<%# Bind("Nombre_PA") %>' Width="92px"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lb_nombrePaciente" runat="server" Text='<%# Bind("Nombre_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="APELLIDO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_ApellidoPaciente" runat="server" Text='<%# Bind("Apellido_PA") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lb_ApellidoNombre" runat="server" Text='<%# Bind("Apellido_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="LOCALIDAD">
                            <ItemTemplate>
                                <asp:Label ID="lb_LocalidadPaciente" runat="server" Text='<%# Bind("Localidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PROVINCIA">
                            <ItemTemplate>
                                <asp:Label ID="lb_IDProvinciaPaciente" runat="server" Text='<%# Bind("Provincia") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DIRECCION">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Direccion" runat="server" Text='<%# Bind("Direccion_PA") %>' Width="107px"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lb_DireccionPaciente" runat="server" Text='<%# Bind("Direccion_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="TELEFONO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Telefono" runat="server" Text='<%# Bind("Telefono_PA") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lb_telefonoPaciente" runat="server" Text='<%# Bind("Telefono_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="EMAIL">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Email" runat="server" Text='<%# Bind("Email_PA") %>' Width="139px"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbEmailPaciente" runat="server" Text='<%# Bind("Email_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NACIONALIDAD">
                            <ItemTemplate>
                                <asp:Label ID="lblNacionalidadPaciente" runat="server" Text='<%# Bind("Nacionalidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="GENERO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Genero" runat="server" Text='<%# Bind("Genero_PA") %>' Width="113px"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblGenero" runat="server" Text='<%# Bind("Genero_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="FECHA DE NACIMIENTO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_fecha" runat="server" Text='<%# Bind("Fecha_Nacimiento_PA") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblfecha" runat="server" Text='<%# Bind("Fecha_Nacimiento_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ESTADO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_estado" runat="server" Text='<%# Bind("Estado_PA") %>' Width="119px"></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblEstado" runat="server" Text='<%# Bind("Estado_PA") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView>
            </div>
        <div>
        </div>
    </form>
</body>
</html>
