<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListadoMedicos.aspx.cs" Inherits="Vistas.ListadoMedicos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .auto-style2 {
        max-width: 4260px;
        max-height: 1000px;
        background-color: #ffffff;
        padding: 25px;
        border-radius: 10px;
        box-shadow: 0 6px 12px rgba(0,0,0,0.1);
            width: 2083px;
            height: 1888px;
        }

    .auto-style1 {
        background-color: #2a6db0;
        color: white;
        font-weight: bold;
        border: none;
        padding: 10px 16px;
        border-radius: 12px;
        cursor: pointer;
        font-size: 0.95rem;
        transition: background-color 0.3s ease;
    }

    .usuario-label {
        font-weight: 600;
        color: #333;
    }

    input[type=text] {
        padding: 8px;
        width: 200px;
        border-radius: 5px;
        border: 1px solid #ccc;
        font-size: 0.95rem;
        margin-right: 10px;
    }

        .auto-style3 {
            border-style: none;
            border-color: inherit;
            border-width: medium;
            background-color: #2a6db0;
            color: white;
            font-weight: bold;
            padding: 10px 16px;
            border-radius: 12px;
            cursor: pointer;
            font-size: 0.95rem;
            transition: background-color 0.3s ease;
            margin-left: 272px;
        }
        .auto-style4 {
            border-style: none;
            border-color: inherit;
            border-width: medium;
            background-color: #2a6db0;
            color: white;
            font-weight: bold;
            padding: 10px 16px;
            border-radius: 12px;
            cursor: pointer;
            font-size: 0.95rem;
            transition: background-color 0.3s ease;
            margin-left: 101px;
        }

    </style>
</head>
<body style="width: 2053px; height: 1854px; margin-bottom: 54px;">
    <form id="form1" runat="server">
        <div>
        <div class="auto-style2">

           
                <div style="display: flex; align-items: center; gap: 10px;">
    <asp:Button ID="Button2" runat="server" CssClass="auto-style1" Text="Volver al menú" Width="133px" OnClick="Button2_Click" />
                    &nbsp;
    <asp:Label ID="lblNombreUsuario" runat="server" CssClass="usuario-label" Font-Size="Large" /></div>
                <br />
                <asp:Label ID="Label2" runat="server" Text="Listado de Medicos" Font-Bold="True" Font-Size="XX-Large"></asp:Label>
                <br />
                <asp:Label ID="Label1" runat="server" Text="Buscar por Legajo" Font-Size="Small"></asp:Label>
                <br />
                <asp:TextBox ID="txtFiltro" runat="server"></asp:TextBox>
                <br />
                <asp:RequiredFieldValidator ID="rfvLegajo" runat="server" ControlToValidate="txtFiltro" ErrorMessage="Ingrese un legajo" ForeColor="Red" ValidationGroup="grupo1"></asp:RequiredFieldValidator>
                <asp:Button ID="btnMostarMedicosActivos" runat="server" CssClass="auto-style3" Text="Mostrar Medicos Activos" Width="237px" OnClick="btnMostarMedicosActivos_Click" />
                <asp:Button ID="btnMostarTodo" runat="server" CssClass="auto-style4" Text="Mostrar todos" Width="158px" OnClick="btnMostarTodo_Click" />
                <br />
                <asp:Button ID="btnFiltar" runat="server" CssClass="auto-style1" Text="Filtrar" Width="113px" OnClick="btnFiltar_Click" ValidationGroup="grupo1" />
                <br />
                Buscar por DNI:<br />
                <asp:TextBox ID="txtFiltroDNI" runat="server"></asp:TextBox>
                <br />
                <asp:RequiredFieldValidator ID="rfvDNI" runat="server" ControlToValidate="txtFiltroDNI" ErrorMessage="Ingrese un dni" ForeColor="Red" ValidationGroup="grupo2"></asp:RequiredFieldValidator>
                <br />
                <asp:Button ID="btnFiltrarDNI" runat="server" CssClass="auto-style1" Text="Filtrar" Width="113px" OnClick="btnFiltrarDNI_Click" ValidationGroup="grupo2" />
                <br />
                <br />
                <asp:GridView ID="gvListadoMedicos"  runat="server" Width="997px" Font-Size="Medium" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderWidth="1px" CellPadding="5" Height="312px"  AllowSorting="True" OnRowUpdating="gvListadoMedicosRowUpdating" OnRowCancelingEdit="gvListadoMedicos_RowCancelingEdit" OnPageIndexChanging="gvListadoMedicos_PageIndexChanging" OnRowEditing="gvListadoMedicos_RowEditing" OnRowDeleting="gvListadoMedicos_RowDeleting" AllowPaging="True">
                    <Columns>
                        <asp:TemplateField HeaderText="LEGAJO">
                            <ItemTemplate>
                                <asp:Label ID="lbl_Legajo" runat="server" Text='<%# Bind("Legajo_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DNI">
                            <ItemTemplate>
                                <asp:Label ID="lbl_DNI" runat="server" Text='<%# Bind("DNI_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NOMBRE">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Nombre" runat="server" Text='<%# Bind("Nombre_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Nombre" runat="server" Text='<%# Bind("Nombre_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="APELLIDO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Apellido" runat="server" Text='<%# Bind("Apellido_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Apellido" runat="server" Text='<%# Bind("Apellido_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="GENERO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Genero" runat="server" Text='<%# Bind("Genero_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Genero" runat="server" Text='<%# Bind("Genero_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="NACIONALIDAD">                            
                            <ItemTemplate>
                                <asp:Label ID="lbl_IdNacionalidad" runat="server" Text='<%# Bind("Nacionalidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="FECHA NACIMIENTO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_FechaNacimiento" runat="server" Text='<%# Bind("Fecha_Nacimiento_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_FechaNacimiento" runat="server" Text='<%# Bind("Fecha_Nacimiento_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DIRECCION">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Direccion" runat="server" Text='<%# Bind("Direccion_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Direccion" runat="server" Text='<%# Bind("Direccion_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="TELEFONO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Telefono" runat="server" Text='<%# Bind("Telefono_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Telefono" runat="server" Text='<%# Bind("Telefono_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ESPECIALIDAD">
                            <ItemTemplate>
                                <asp:Label ID="lbl_Especialidad" runat="server" Text='<%# Bind("Especialidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="LOCALIDAD">
                            <ItemTemplate>
                                <asp:Label ID="lbl_Localidad" runat="server" Text='<%# Bind("Localidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="USUARIO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Usuario" runat="server" Text='<%# Bind("UsuarioMedico_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Usuario" runat="server" Text='<%# Bind("UsuarioMedico_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ESTADO">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_Estado" runat="server" Text='<%# Bind("Estado_MED") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_Estado" runat="server" Text='<%# Bind("Estado_MED") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PROVINCIA">
                            <ItemTemplate>
                                <asp:Label ID="lbl_Provincia" runat="server" Text='<%# Bind("Provincia") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView>
                <br />
                <asp:Label ID="lbMensaje" runat="server"></asp:Label>
            </div>
        </div>
    </form>
</body>
</html>
